name: angel3_cli
version: 3.0.0-beta.1
description: Command-line tools for the Angel framework, including scaffolding.
homepage: https://github.com/dukefirehawk/angel3_cli
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  analyzer: ^1.7.0
  args: ^2.1.1
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  glob: ^2.0.1
  http: ^0.13.3
  io: ^1.0.0
  inflection3: ^0.5.3+2
  #mustache4dart2: ^0.1.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  prompts: ^2.0.0
  pubspec_parse: ^1.0.0
  quiver: ^3.0.1
  recase: ^4.0.0
  shutdown: ^0.4.3
  watcher: ^1.0.0
  yaml: ^3.1.0
dev_dependencies:
  pedantic: ^1.11.0
executables: 
  angel3: angel3
